server:
  port: 8001

spring:
  application:
    name: short_chains
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://app_mysql:3306/item_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: test
    password: rzny0cB18&E+
  redis:
    host: app_redis
    port: 6379
    timeout: 1000
    connectTimeout: 1000
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.short_chains.pojo

system:
  addr: localhost